name: "Sigrid CI"
description: "Sigrid: getting software right"

inputs:
  customer:
    description: "Your Sigrid customer name."
    required: true
  system:
    description: "Your Sigrid system name."
    required: true
  source:
    description: "Source code directory."
    required: false
    default: "."
  targetquality:
    description: "Minimum required star rating for new/changed code."
    required: false
    default: "3.5"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - "--customer"
    - ${{ inputs.customer }}
    - "--system"
    - ${{ inputs.system }}
    - "--source"
    - ${{ inputs.source }}
    - "--targetquality"
    - ${{ inputs.targetquality }}
