name: sigrid-pullrequest
on: [pull_request]
jobs:
  sigridci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: "Run Sigrid CI" 
        env:
          SIGRID_CI_TOKEN: "${{ secrets.SIGRID_CI_TOKEN }}"
        run: "./sigridci/sigridci.py --customer sig --system sigridci-client --source . --targetquality 3.5"
      - name: "Save Sigrid CI results"
        if: ${{ success() || failure() }}
        uses: actions/upload-artifact@v2
        with:
          path: "sigrid-ci-output/**"
          retention-days: 7
          if-no-files-found: ignore
